# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  C:/540_proj2/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/hdl_part1/world_map.v
  C:/540_proj2/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/hdl_part1/world_if.v
  C:/540_proj2/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/hdl_part1/map.v
  C:/540_proj2/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/hdl_part1/bot_pgm.v
  C:/540_proj2/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/sevensegment.v
  C:/540_proj2/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/nexys4_bot_if.v
  C:/540_proj2/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/hdl_part1/bot.v
  C:/540_proj2/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/debounce.v
  C:/540_proj2/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/nexys4fpga_main.v
}
read_xdc C:/540_proj2/project2_release_r0/project_2/project_2.srcs/constrs_1/imports/constraints/nexys4fpga_novideo.xdc
set_property used_in_implementation false [get_files C:/540_proj2/project2_release_r0/project_2/project_2.srcs/constrs_1/imports/constraints/nexys4fpga_novideo.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/540_proj2/project2_release_r0/project_2/project_2.cache/wt [current_project]
set_property parent.project_dir C:/540_proj2/project2_release_r0/project_2 [current_project]
catch { write_hwdef -file nexys4_main.hwdef }
synth_design -top nexys4_main -part xc7a100tcsg324-1
write_checkpoint nexys4_main.dcp
report_utilization -file nexys4_main_utilization_synth.rpt -pb nexys4_main_utilization_synth.pb
