# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/ece540/project_2/project_2.cache/wt [current_project]
set_property parent.project_path D:/ece540/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/ece540/project_2/project_2.srcs/sources_1/imports/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/hdl_part1/world_map.v
  D:/ece540/project_2/project_2.srcs/sources_1/new/icon_rom.v
  D:/ece540/project_2/project_2.srcs/sources_1/imports/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/hdl_part1/world_if.v
  D:/ece540/project_2/project_2.srcs/sources_1/imports/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/hdl_part1/map.v
  D:/ece540/project_2/project_2.srcs/sources_1/imports/Verilog/kcpsm6.v
  D:/ece540/project_2/project_2.srcs/sources_1/imports/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/hdl_part1/bot_pgm.v
  D:/ece540/project_2/project_2.srcs/sources_1/new/icon.v
  D:/ece540/project_2/project_2.srcs/sources_1/imports/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/hdl_part1/proj2demo.v
  D:/ece540/project_2/project_2.srcs/sources_1/new/nexys4_bot_if.v
  {D:/ece540/project_2/project_2.srcs/sources_1/imports/ECE540/Project 2 all files/project2_release_r0/hdl_part2/dtg.v}
  D:/ece540/project_2/project_2.srcs/sources_1/imports/project2_release_r0/debounce.v
  D:/ece540/project_2/project_2.srcs/sources_1/imports/ECE540/colorizer.v
  D:/ece540/project_2/project_2.srcs/sources_1/imports/project2_release_r0/project_2/project_2.srcs/sources_1/imports/project2_release_r0/hdl_part1/bot.v
  D:/ece540/project_2/project_2.srcs/sources_1/imports/project2_release_r0/sevensegment.v
  D:/ece540/project_2/project_2.srcs/sources_1/new/nexys4fpga.v
}
read_edif D:/ece540/project_2/project_2.srcs/sources_1/imports/world_map_part1/world_map.ngc
read_xdc D:/ece540/project_2/project_2.srcs/constrs_1/imports/constraints/nexys4fpga_withvideo.xdc
set_property used_in_implementation false [get_files D:/ece540/project_2/project_2.srcs/constrs_1/imports/constraints/nexys4fpga_withvideo.xdc]

catch { write_hwdef -file nexys4fpga.hwdef }
synth_design -top nexys4fpga -part xc7a100tcsg324-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off
write_checkpoint nexys4fpga.dcp
catch { report_utilization -file nexys4fpga_utilization_synth.rpt -pb nexys4fpga_utilization_synth.pb }
