set_property SRC_FILE_INFO {cfile:C:/540_proj2/project2_release_r0/project_1/project_1.srcs/constrs_1/imports/constraints/nexys4fpga_novideo.xdc rfile:../../../project_1.srcs/constrs_1/imports/constraints/nexys4fpga_novideo.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports dp]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports dp]
