# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  C:/540_proj2/project2_release_r0/project_1/project_1.srcs/sources_1/imports/project2_release_r0/hdl_part1/world_map.v
  C:/540_proj2/project2_release_r0/project_1/project_1.srcs/sources_1/imports/project2_release_r0/hdl_part1/world_if.v
  C:/540_proj2/project2_release_r0/project_1/project_1.srcs/sources_1/imports/project2_release_r0/hdl_part1/map.v
  C:/540_proj2/project2_release_r0/project_1/project_1.srcs/sources_1/imports/project2_release_r0/hdl_part1/bot_pgm.v
  C:/540_proj2/project2_release_r0/project_1/project_1.srcs/sources_1/imports/KCPSM6_Release9_30Sept14/Verilog/kcpsm6.v
  C:/540_proj2/project2_release_r0/project_1/project_1.srcs/sources_1/imports/project2_release_r0/sevensegment.v
  C:/540_proj2/project2_release_r0/project_1/project_1.srcs/sources_1/imports/project2_release_r0/nexys4_bot_if.v
  C:/540_proj2/project2_release_r0/project_1/project_1.srcs/sources_1/imports/project2_release_r0/hdl_part1/proj2demo.v
  C:/540_proj2/project2_release_r0/project_1/project_1.srcs/sources_1/imports/project2_release_r0/hdl_part1/bot.v
  C:/540_proj2/project2_release_r0/project_1/project_1.srcs/sources_1/imports/project2_release_r0/debounce.v
  C:/540_proj2/project2_release_r0/project_1/project_1.srcs/sources_1/imports/project2_release_r0/nexys4fpga_main.v
}
read_edif C:/540_proj2/project2_release_r0/project_1/project_1.srcs/sources_1/imports/world_map_part1/world_map.ngc
read_xdc C:/540_proj2/project2_release_r0/project_1/project_1.srcs/constrs_1/imports/constraints/nexys4fpga_novideo.xdc
set_property used_in_implementation false [get_files C:/540_proj2/project2_release_r0/project_1/project_1.srcs/constrs_1/imports/constraints/nexys4fpga_novideo.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/540_proj2/project2_release_r0/project_1/project_1.cache/wt [current_project]
set_property parent.project_dir C:/540_proj2/project2_release_r0/project_1 [current_project]
catch { write_hwdef -file nexys4fpga_main.hwdef }
synth_design -top nexys4fpga_main -part xc7a100tcsg324-1
write_checkpoint nexys4fpga_main.dcp
report_utilization -file nexys4fpga_main_utilization_synth.rpt -pb nexys4fpga_main_utilization_synth.pb
